version: '3.8'

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-api
    ports:
      - "${WA_SERVER_PORT:-8000}:8000"
    environment:
      - WA_SERVER_HOST=0.0.0.0
      - WA_SERVER_PORT=${WA_SERVER_PORT:-8000}
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - wa-session:/app/sessions
    user: "node"
    restart: unless-stopped

volumes:
  wa-session: